package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class p1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>JCF Showcase</title>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t\t<meta name=\"description\" content=\"jcf showcase\">\r\n");
      out.write("\t\t<meta name=\"author\" content=\"jcf\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Le styles -->\r\n");
      out.write("\t\t<link href=\"assets/bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"assets/bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"assets/bootstrap/css/docs.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"assets/bootstrap/css/prettify.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"assets/css/jquery-ui-1.9.2.custom.css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 공통 lib-->\r\n");
      out.write("\t\t<script src=\"lib/jquery-1.9.0.js\"></script>\r\n");
      out.write("\t\t<script src=\"lib/jquery-ui-1.9.2.custom.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/bootstrap/js/prettify.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/bootstrap/js/application.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/p1.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body data-spy=\"scroll\" data-target=\".bs-docs-sidebar\">\r\n");
      out.write("\t\t<!-- Navbar -->\r\n");
      out.write("\t\t<div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("\t\t\t<div class=\"navbar-inner\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<a class=\"brand\" href=\"/jcf-showcase/index.html\">JCF-Showcase</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"\"><a href=\"/jcf-showcase/index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a href=\"/jcf-showcase/openpage.do?viewname=p1\">JCF SUA</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"\"><a href=\"/jcf-showcase/openpage.do?viewname=p2\">파일업로드/다운로드</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"\"><a href=\"/jcf-showcase/openpage.do?viewname=p3\">대용량조회</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"\"><a href=\"/jcf-showcase/openpage.do?viewname=p4\">예외 및 메시지처리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"\"><a href=\"openpage.do?viewname=p5\">JCF Query </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"\"><a href=\"openpage.do?viewname=p6\">활용 CASE</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"\"><a href=\"#\">JCF-IAM(개발예정)</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Subhead -->\r\n");
      out.write("\t\t<header id=\"overview\"> </header>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!-- Docs nav -->\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"span3 bs-docs-sidebar\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-list bs-docs-sidenav\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#p10\"> <i class=\"icon-chevron-right\"></i>Overview</a>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#p11\"> <i class=\"icon-chevron-right\"></i>MCI Request</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#p11_3\">단건 데이터 Bean Type 으로 받기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#p11_4\">단건 데이터 Bean Type 으로 받기<br/>(Form 전송인 경우)</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#p11_5\">단건 데이터 Map 으로 받기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#p11_6\">단건 데이터 Map 으로 받기<br/>(Form 전송일 경우)</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#p11_7\">다건 데이터 Bean Type 으로 받기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#p11_8\">다건 데이터 Map 으로 받기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#p11_9\">Request URL 정보 얻어오기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#p12\"><i class=\"icon-chevron-right\"></i>MCI Response </a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#p12_1\">단건 데이터 String Type 으로 보내기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#p12_2\">단건 데이터 Bean Type 으로 보내기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#p12_3\">단건 데이터 Map Type 으로 보내기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#p12_4\">다건 데이터 Bean Type 으로 보내기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#p12_5\">다건 데이터 Map Type 으로 보내기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#p12_6\">Redirect 페이지 호출하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"span9\">\r\n");
      out.write("\t          \t<br/>\r\n");
      out.write("\t\t\t\t<!-- Request Mapping -->\r\n");
      out.write("\t        \t<section id=\"p10\">\r\n");
      out.write("\t        \t\t<div  class=\"page-header\">\r\n");
      out.write("\t\t\t\t\t\t<h3>개요</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tJCF-SUA(Smart UI Adaptor)는 단일 서비스로 웹표준, X-인터넷, 모바일 등 다양한 UI 클라이언트와\r\n");
      out.write("\t\t\t\t\t\t연동할 수 있는 다중 채널을 제공하며 이를 통해 개발자는 UI 기술과는 독립적으로 동일한 인터페이스를 통해 서버 측 애플리케이션을 개발 할 수 있다.\r\n");
      out.write("\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t현재 제공하는 UI는 웹표준, JSON, Miplatform, XPlatform, WebPlus, WebSquare, Mybuilder Flex, EXT-JS, Gauce 등이 있으며\r\n");
      out.write("\t\t\t\t\t\t본 예제에서는 JSON과 표준웹 방식을 예제로 설명한다.\r\n");
      out.write("\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t관련 코드는 com.jcf.sample.sua 패키지에 자세히 나와있다.\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("&lt;!-- jcf-sua 를 사용한 xml 설정  --&gt;\r\n");
      out.write("&lt;jcfsua:sua-config auto-config=\"false\" webflow-prefix=\"/WEB-INF/views/\" webflow-suffix=\".jsp\"&gt;\r\n");
      out.write("\t&lt;jcfsua:channel channel-type=\"EXTJS\"/&gt;\r\n");
      out.write("\t&lt;jcfsua:channel channel-type=\"JSON\"/&gt;\r\n");
      out.write("\t&lt;jcfsua:channel channel-type=\"WEBFLOW\"/&gt;\r\n");
      out.write("\t&lt;jcfsua:custom-interceptor ref=\"localeChangeInterceptor\"/&gt;\r\n");
      out.write("&lt;/jcfsua:sua-config&gt;\r\n");
      out.write("\t\t\t\t\t</pre>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t<section id=\"p11\">\r\n");
      out.write("\t\t\t\t\t<div  class=\"page-header\">\r\n");
      out.write("\t\t\t\t\t\t<h3>MCI Request</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>JCF-SUA 서비스를 통해 웹 요청을 받는 방식에 대해서 설명한다.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t \t          \t<section id=\"p11_3\">\r\n");
      out.write("\t\t\t\t\t\t<h4 id=\"headings\">단건 데이터 Bean Type 으로 받기</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>Form 형태의 단건 데이터를 JSON 형태로 변환하여 JavaBean 형태로 받는다.<br/>\r\n");
      out.write("\t\t\t\t\t\t   jcf.sua.mvc.MciRequest.get(String datasetId, Class class)</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-docs-example\" id=\"p11_3\">\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t<form id=\"p11_3_Form\" class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"p11_3_param1\">아이디</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"param1\" id=\"p11_3_param1\" placeholder=\"아이디\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"p11_3_param2\">나이</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"param2\" id=\"p11_3_param2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonBlur=onlyNumber(this) placeholder=\"나이(숫자)\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"p11_3_param3\">등록일자</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input name=\"param3\" type=\"text\" id=\"p11_3_param3\" /> <br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"btn\" type=\"submit\" id=\"p11_3_btn1\">전송</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"p11_3_result\" class=\"bs-docs-example-result\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("@RequestMapping(\"/getJavaBean\")\r\n");
      out.write("public void getJavaBean(MciRequest request, MciResponse response) {\r\n");
      out.write("\tSuaBean javaBean = request.get(\"DS_IN\", SuaBean.class);\r\n");
      out.write("\r\n");
      out.write("\tresponse.addSuccessMessage(\"요청받은 데이터는 \" + javaBean.toString() + \" 입니다.\");\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t          \t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t                <section id=\"p11_4\">\r\n");
      out.write("\t\t\t\t\t\t<h4 id=\"headings\">단건 데이터 Bean Type 으로 받기 (Form 전송인 경우)</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\tForm 형태의 단건 데이터를 JavaBean 형태로 받은 후 다른 페이지로 전환한다. <br />\r\n");
      out.write("\t\t\t\t\t\t\tjcf.sua.mvc.MciRequest.getParam(Class class)\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-docs-example\">\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t<div  id=\"p11_4_iframe\" class=\"form-horizontal\">\r\n");
      out.write("\t                        \t<iframe src=\"openpage.do?viewname=p1_iframe_1\" width=\"500\" height=\"250\" name=\"main\" style=\"border:0;\"></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("@RequestMapping(\"/getFormData\")\r\n");
      out.write("public void getFormData(MciRequest request, MciResponse response) {\r\n");
      out.write("\tSuaBean javaBean = request.getParam(SuaBean.class);\r\n");
      out.write("\r\n");
      out.write("\tresponse.addParam(\"DS_OUT\", \"요청받은 데이터는 \" + javaBean.toString() + \" 입니다.\");\r\n");
      out.write("\tresponse.setViewName(\"/redirect/p1_iframe_1_Succuss\");\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<section id=\"p11_5\">\r\n");
      out.write("\t\t\t\t\t\t<h4 id=\"headings\">단건 데이터 Map 으로 받기</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\tForm 형태의 단건 데이터를 JSON 형태로 변환하여 Map 형태로 받는다. <br />\r\n");
      out.write("\t\t\t\t\t\t\tjcf.sua.mvc.MciRequest.getMap(String datasetId)\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-docs-example\" >\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t<form id=\"p11_5_Form\" class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"p11_5_param1\">아이디</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"param1\" id=\"p11_5_param1\" placeholder=\"아이디\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"p11_5_param2\">나이</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"param2\" id=\"p11_5_param2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonBlur=onlyNumber(this) placeholder=\"나이(숫자)\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"p11_5_param3\">등록일자</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"param3\" id=\"p11_5_param3\" /> <br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"btn\" type=\"submit\" id=\"p11_5_btn1\">전송</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"p11_5_result\" class=\"bs-docs-example-result\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("@RequestMapping(\"/getMap\")\r\n");
      out.write("public void getMap(MciRequest request, MciResponse response) {\r\n");
      out.write("\tMap map = request.getMap(\"DS_IN\");\r\n");
      out.write("\r\n");
      out.write("\tString name = String.valueOf(map.get(\"name\"));\r\n");
      out.write("\tString age = String.valueOf(map.get(\"age\"));\r\n");
      out.write("\tString regiDate = String.valueOf(map.get(\"regiDate\"));\r\n");
      out.write("\r\n");
      out.write("\tresponse.addSuccessMessage(\"요청받은 Map 유형의 데이터는 아이디 : \" + name + \" 나이 : \" + age + \" 등록일자 : \" + regiDate + \" 입니다.\");\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t          \t\t<section id=\"p11_6\">\r\n");
      out.write("\t\t\t\t\t\t<h4 id=\"headings\">단건 데이터 Map 으로 받기 (Form 전송일 경우)</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\tForm 형태의 단건 데이터를 Map 형태로 받은 후 다른 페이지로 전환한다. <br />\r\n");
      out.write("\t\t\t\t\t\t\tjcf.sua.mvc.MciRequest.getMap(String datasetId)\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-docs-example\">\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t<div  id=\"p11_6_iframe\">\r\n");
      out.write("\t                        \t<iframe src=\"/jcf-showcase/openpage.do?viewname=p1_iframe_2\"  width=\"500\" height=\"220\" name=\"main\" style=\"border:0;\"></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("@RequestMapping(\"/getMapForm\")\r\n");
      out.write("public void getMapForm(MciRequest request, MciResponse response) {\r\n");
      out.write("\tMap map = request.getParam();\r\n");
      out.write("\r\n");
      out.write("\tString name = String.valueOf(map.get(\"name\"));\r\n");
      out.write("\tString age = String.valueOf(map.get(\"age\"));\r\n");
      out.write("\r\n");
      out.write("\tresponse.addParam(\"DS_OUT\", \"요청받은 Map 유형의 데이터는 아이디 : \" + name + \" 나이 : \" + age + \" 입니다.\");\r\n");
      out.write("\tresponse.setViewName(\"/redirect/p1_iframe_2_Succuss\");\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<section id=\"p11_7\">\r\n");
      out.write("\t\t\t\t\t\t<h4 id=\"headings\">다건 데이터 Bean Type 으로 받기</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t테이블 형태의 다건 데이터를 JSON 형태로 변환하여 GirdData 형태로 받는다.<br />\r\n");
      out.write("\t\t\t\t\t\t\tjcf.sua.mvc.MciRequest.getGridData(String datasetId, Class class)\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-docs-example\">\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"p11_7_form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>나이</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>생일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>RowStatus</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_7_param1_1\" value=\"sample1\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_7_param1_2\" value=\"23\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_7_param1_3\" value=\"2013/01/14\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"p11_7_param1_4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"INSERT\" selected=\"selected\">입력</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"UPDATE\">수정</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"DELETE\">삭제</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_7_param2_1\" value=\"sample2\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_7_param2_2\" value=\"30\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_7_param2_3\" value=\"2011/03/09\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"p11_7_param2_4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"INSERT\">입력</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"UPDATE\" selected=\"selected\">수정</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"DELETE\">삭제</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_7_param3_1\" value=\"sample3\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_7_param3_2\" value=\"47\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_7_param3_3\" value=\"2012/04/23\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"p11_7_param3_4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"INSERT\">입력</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"UPDATE\" >수정</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"DELETE\" selected=\"selected\">삭제</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn\" type=\"submit\" id=\"p11_7_btn1\">전송</button>\r\n");
      out.write("\t\t\t\t\t\t\t<br/><br/>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"p11_7_result\" class=\"bs-docs-example-result\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("@RequestMapping(\"/getJavaBeans\")\r\n");
      out.write("public void getJavaBeans(MciRequest request, MciResponse response) {\r\n");
      out.write("\tGridData&lt;SuaBean&gt; javaBeans = request.getGridData(\"DS_IN\", SuaBean.class);\r\n");
      out.write("\r\n");
      out.write("\tint insertRow = 0;\r\n");
      out.write("\tint updateRow = 0;\r\n");
      out.write("\tint deleteRow = 0;\r\n");
      out.write("\r\n");
      out.write("\tfor (int i = 0; i &lt; javaBeans.size(); i++) {\r\n");
      out.write("\t\tif (RowStatus.INSERT.equals(javaBeans.getStatusOf(i))) {\r\n");
      out.write("\t\t\tinsertRow++;\r\n");
      out.write("\t\t} else if (RowStatus.UPDATE.equals(javaBeans.getStatusOf(i))) {\r\n");
      out.write("\t\t\tupdateRow++;\r\n");
      out.write("\t\t} else if (RowStatus.DELETE.equals(javaBeans.getStatusOf(i))) {\r\n");
      out.write("\t\t\tdeleteRow++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tresponse.addSuccessMessage(\"총 건수 : \" + javaBeans.size() + \" 건, INSERT 건수 : \" + insertRow + \"건, UPDATE 건수 : \"+ updateRow+\"건, delete 건수 : \" + deleteRow);\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<section id=\"p11_8\">\r\n");
      out.write("\t\t\t\t\t\t<h4 id=\"headings\">다건 데이터 Map 으로 받기</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t테이블 형태의 다건 데이터를 JSON 형태로 변환하여 GirdData&lt;Map&gt; 형태로 받는다.<br />\r\n");
      out.write("\t\t\t\t\t\t\tjcf.sua.mvc.MciRequest.getGridData(String datasetId, HashMap class)\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-docs-example\" id=\"p11_8\">\r\n");
      out.write("\t\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"p11_8_form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>나이</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>생일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>RowStatus</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_8_param1_1\" value=\"sample1\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_8_param1_2\" value=\"15\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_8_param1_3\" value=\"2013/01/14\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"p11_8_param1_4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"INSERT\" selected=\"selected\">입력</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"UPDATE\">수정</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"DELETE\">삭제</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_8_param2_1\" value=\"sample2\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_8_param2_2\" value=\"30\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_8_param2_3\" value=\"1980/04/23\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"p11_8_param2_4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"INSERT\">입력</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"UPDATE\" selected=\"selected\">수정</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"DELETE\">삭제</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_8_param3_1\" value=\"sample3\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_8_param3_2\" value=\"48\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"p11_8_param3_3\" value=\"2011/06/05\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"p11_8_param3_4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"INSERT\">입력</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"UPDATE\" >수정</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"DELETE\" selected=\"selected\">삭제</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn\" type=\"submit\" id=\"p11_8_btn1\">전송</button>\r\n");
      out.write("\t\t\t\t\t\t\t<br/><br/>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"p11_8_result\" class=\"bs-docs-example-result\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("@RequestMapping(\"/getMapList\")\r\n");
      out.write("public void getMapList(MciRequest request, MciResponse response) {\r\n");
      out.write("\tGridData&lt;HashMap&gt; javaBeans = request.getGridData(\"DS_IN\", HashMap.class);\r\n");
      out.write("\r\n");
      out.write("\tint insertRow = 0;\r\n");
      out.write("\tint updateRow = 0;\r\n");
      out.write("\tint deleteRow = 0;\r\n");
      out.write("\r\n");
      out.write("\tfor (int i = 0; i &lt; javaBeans.size(); i++) {\r\n");
      out.write("\t\tif (RowStatus.INSERT.equals(javaBeans.getStatusOf(i))) {\r\n");
      out.write("\t\t\tinsertRow++;\r\n");
      out.write("\t\t} else if (RowStatus.UPDATE.equals(javaBeans.getStatusOf(i))) {\r\n");
      out.write("\t\t\tupdateRow++;\r\n");
      out.write("\t\t} else if (RowStatus.DELETE.equals(javaBeans.getStatusOf(i))) {\r\n");
      out.write("\t\t\tdeleteRow++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tresponse.addSuccessMessage(\"총 건수 : \" + javaBeans.size() + \"건, INSERT 건수 : \" + insertRow + \"건, UPDATE 건수 : \"+ updateRow + \"건, delete 건수 : \" + deleteRow);\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<section id=\"p11_9\">\r\n");
      out.write("\t\t\t\t\t\t<h4 id=\"headings\">Request URL 정보 얻어오기</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t요청받은\tHttpResquest 에 대한  URL 정보를 얻어온다. <br />\r\n");
      out.write("\t\t\t\t\t\t\tjcf.sua.mvc.MciRequest.getRequestURI()\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-docs-example\" >\r\n");
      out.write("\t\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn\" id=\"p11_9_btn1\">요청보내기</button>\r\n");
      out.write("\t\t\t\t\t\t\t<br/><br/>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"p11_9_result\" class=\"bs-docs-example-result\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("@RequestMapping(\"/getRequestURL\")\r\n");
      out.write("public void getRequestURL(MciRequest request, MciResponse response){\r\n");
      out.write("\tString requestUrl=request.getRequestURI();\r\n");
      out.write("\tresponse.addSuccessMessage(\"요청 받은 URL 주소는 \" + requestUrl + \"입니다.\");\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t       \t<section id=\"p12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"page-header\">\r\n");
      out.write("\t\t\t\t\t\t<h3>MciResponse</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>JCF-SUA 서비스를 통해 웹에 데이터를 보내는 방식에 대해서 설명한다.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<section id=\"p12_1\">\r\n");
      out.write("\t\t\t\t\t\t<h4 id=\"headings\">단건 데이터 String Type 으로 보내기</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>브라우저로 String 유형의 데이터를 보낸다.<br/>\r\n");
      out.write("\t\t\t\t\t\t\tjcf.sua.mvc.MciResponse.addParam(String paramId, paramValue)\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-docs-example\">\r\n");
      out.write("\t\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn\" id=\"p12_1_btn1\">조회</button>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\tparam : <input type=\"text\"\tname=\"param\" id=\"p12_1_param1\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("@RequestMapping(\"/sendStringData\")\r\n");
      out.write("public void sendStringData(MciRequest request, MciResponse response){\r\n");
      out.write("\tresponse.addParam(\"param1\", \"테스트 데이터\");\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t<section id=\"p12_2\">\r\n");
      out.write("\t\t\t\t\t\t<h4 id=\"headings\">단건 데이터 Bean Type 으로 보내기</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>브라우저로 JavaBean 유형의 데이터를 보낸다.<br/>\r\n");
      out.write("\t\t\t\t\t\t\tjcf.sua.mvc.MciResponse.set(String datasetId, JavaBean javabean)\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-docs-example\">\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn\" type=\"submit\" id=\"p12_2_btn1\">조회</button>\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t<form id=\"p12_2_Form\" class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"p12_2_param1\">아이디</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"param1\" id=\"p12_2_param1\" placeholder=\"아이디\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"p12_2_param2\">나이</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"param2\" id=\"p12_2_param2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonBlur=onlyNumber(this) placeholder=\"나이(숫자)\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"p12_2_param3\">등록일자</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input name=\"param3\" type=\"text\" id=\"p12_2_param3\" /> <br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("@RequestMapping(\"/sendJavaBean\")\r\n");
      out.write("public void sendJavaBean(MciRequest request, MciResponse response) {\r\n");
      out.write("\tSuaBean javaBean = new SuaBean(\"sample\", 24, \"2012/02/01\");\r\n");
      out.write("\r\n");
      out.write("\tresponse.set(\"DS_OUT\", javaBean);\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t              \t<section id=\"p12_3\">\r\n");
      out.write("\t\t\t\t\t\t<h4 id=\"headings\">단건 데이터 Map Type 으로 보내기</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>브라우저로 Map 유형의 데이터를 보낸다.<br/>\r\n");
      out.write("\t\t\t\t\t\t\tjcf.sua.mvc.MciResponse.setMap(String datasetId, Map data)\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-docs-example\">\r\n");
      out.write("\t\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn\" type=\"submit\" id=\"p12_3_btn1\">조회</button>\r\n");
      out.write("\t\t\t\t\t\t\t<form id=\"p12_2_Form\" class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"p12_3_param1\">아이디</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"param1\" id=\"p12_3_param1\" placeholder=\"아이디\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"p12_3_param2\">나이</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"param2\" id=\"p12_3_param2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonBlur=onlyNumber(this) placeholder=\"나이(숫자)\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"p12_3_param3\">등록일자</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input name=\"param3\" type=\"text\" id=\"p12_3_param3\" /> <br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("@RequestMapping(\"/sendMap\")\r\n");
      out.write("public void sendMap(MciRequest request, MciResponse response) {\r\n");
      out.write("\tMap&lt;String, Object&gt; data = new HashMap&lt;String, Object&gt;();\r\n");
      out.write("\r\n");
      out.write("\tdata.put(\"name\", \"sample\");\r\n");
      out.write("\tdata.put(\"age\", 32);\r\n");
      out.write("\tdata.put(\"regiDate\", \"2012/02/25\");\r\n");
      out.write("\r\n");
      out.write("\tresponse.setMap(\"DS_OUT\", data);\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t           \t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t           \t\t<section id=\"p12_4\">\r\n");
      out.write("\t\t\t\t\t\t<h4 >다건 데이터 Bean Type 으로 보내기</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>브라우저로 Bean 객체가 있는 리스트 형태의 다건의 데이터를 보낸다.<br/>\r\n");
      out.write("\t\t\t\t\t\t\tjcf.sua.mvc.MciResponse.setList(String datasetId, List data)\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-docs-example\" >\r\n");
      out.write("\t\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn\" type=\"submit\" id=\"p12_4_btn1\">조회</button>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"p11_8_form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>나이</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>등록일자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("@RequestMapping(\"/sendJavaBeanList\")\r\n");
      out.write("public void sendJavaBeanList(MciRequest request, MciResponse response) {\r\n");
      out.write("\tSuaBean javaBean1 = new SuaBean(\"test1\", 16, \"2010/02/01\");\r\n");
      out.write("\tSuaBean javaBean2 = new SuaBean(\"test2\", 23, \"2012/03/03\");\r\n");
      out.write("\tSuaBean javaBean3 = new SuaBean(\"test3\", 49, \"2013/01/31\");\r\n");
      out.write("\r\n");
      out.write("\tList&lt;SuaBean&gt; list = new ArrayList&lt;SuaBean&gt;();\r\n");
      out.write("\r\n");
      out.write("\tlist.add(javaBean1);\r\n");
      out.write("\tlist.add(javaBean2);\r\n");
      out.write("\tlist.add(javaBean3);\r\n");
      out.write("\r\n");
      out.write("\tresponse.setList(\"DS_OUT\", list);\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t      \t\t\t<section id=\"p12_5\">\r\n");
      out.write("\t\t\t\t\t\t<h4 id=\"headings\">다건 데이터 Map Type 으로 보내기</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>브라우저로 Map 객체가 있는 리스트 형태의 다건의 데이터를 보낸다.<br/>\r\n");
      out.write("\t\t\t\t\t\tjcf.sua.mvc.MciResponse.setMapList(String datasetId, List&lt;HashMap&gt; data)\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-docs-example\" >\r\n");
      out.write("\t\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn\" type=\"submit\" id=\"p12_5_btn1\">조회</button>\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>나이</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>등록일자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("@RequestMapping(\"/sendMapList\")\r\n");
      out.write("public void sendMapList(MciRequest request, MciResponse response) {\r\n");
      out.write("\tMap&lt;String, String&gt; data1 = new HashMap&lt;String, String&gt;();\r\n");
      out.write("\r\n");
      out.write("\tdata1.put(\"name\", \"sample1\");\r\n");
      out.write("\tdata1.put(\"age\", \"23\");\r\n");
      out.write("\tdata1.put(\"regiDate\", \"2012/02/25\");\r\n");
      out.write("\r\n");
      out.write("\tMap&lt;String, String&gt; data2 = new HashMap&lt;String, String&gt;();\r\n");
      out.write("\r\n");
      out.write("\tdata2.put(\"name\", \"sample2\");\r\n");
      out.write("\tdata2.put(\"age\", \"45\");\r\n");
      out.write("\tdata2.put(\"regiDate\", \"2013/05/25\");\r\n");
      out.write("\r\n");
      out.write("\tMap&lt;String, String&gt; data3 = new HashMap&lt;String, String&gt;();\r\n");
      out.write("\r\n");
      out.write("\tdata3.put(\"name\", \"sample3\");\r\n");
      out.write("\tdata3.put(\"age\", \"54\");\r\n");
      out.write("\tdata3.put(\"regiDate\", \"2010/01/25\");\r\n");
      out.write("\r\n");
      out.write("\tList&lt;Map&lt;String, String&gt;&gt; list = new ArrayList&lt;Map&lt;String, String&gt;&gt;();\r\n");
      out.write("\r\n");
      out.write("\tlist.add(data1);\r\n");
      out.write("\tlist.add(data2);\r\n");
      out.write("\tlist.add(data3);\r\n");
      out.write("\r\n");
      out.write("\tresponse.setMapList(\"DS_OUT\", list);\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t      \t\t\t<section id=\"p12_6\">\r\n");
      out.write("\t\t\t\t\t\t<h4 id=\"headings\">Redirect 페이지 호출하기</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>AJAX 통신이 아니라 일반 웹페이지 통신일 경우 다른 페이지로 이동시킨다. 페이지 경로는\r\n");
      out.write("\t\t\t\t\t\t\tjcf-context.xml 파일에서 설정한 webflow-prefix 경로를 base 폴더로 한다.<br/>\r\n");
      out.write("\t\t\t\t\t\t\tjcf.sua.mvc.MciResponse.setViewName(String viewName)\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-docs-example\" id=\"p12_6\">\r\n");
      out.write("\t\t\t\t\t   \t\t<iframe src=\"openpage.do?viewname=p1_iframe_3\" width=\"500\" height=\"180\" name=\"main\" name=\"main\" style=\"border:0;\"></iframe>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("@RequestMapping(\"/redirectPage\")\r\n");
      out.write("public void redirectPage(MciRequest request, MciResponse response){\r\n");
      out.write("\tresponse.setViewName(\"/redirect/p1_iframe_3_Succuss\");\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t\t\t\t\t\t<pre class=\"prettyprint linenums\">\r\n");
      out.write("\r\n");
      out.write("\t&lt;jcfsua:sua-config auto-config=\"true\" webflow-prefix=\"/WEB-INF/views/\" webflow-suffix=\".jsp\" &gt;\r\n");
      out.write("\t\t\t\t\t\t</pre>\r\n");
      out.write("\t          \t\t</section>\r\n");
      out.write("\t \t\t\t</section>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t<footer class=\"footer\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<p> Homepage : <a href=\"http://jcf.daewoobrenic.co.kr/blog/\">JCF Blog</a></p>\r\n");
      out.write("\t        \t<p> E-Mail : <a href=\"mailto:jcf@disc.co.kr\">jcf@disc.co.kr</a></p>\r\n");
      out.write("\t        \t<p>Copyright © 2013 Daewoo Information Systems Co., Ltd..</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Analytics -->\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tvar _gauges = _gauges || [];\r\n");
      out.write("\t\t\t(function() {\r\n");
      out.write("\t\t\t\tvar t = document.createElement('script');\r\n");
      out.write("\t\t\t\tt.type = 'text/javascript';\r\n");
      out.write("\t\t\t\tt.async = true;\r\n");
      out.write("\t\t\t\tt.id = 'gauges-tracker';\r\n");
      out.write("\t\t\t\tt.setAttribute('data-site-id', '4f0dc9fef5a1f55508000013');\r\n");
      out.write("\t\t\t\tt.src = '//secure.gaug.es/track.js';\r\n");
      out.write("\t\t\t\tvar s = document.getElementsByTagName('script')[0];\r\n");
      out.write("\t\t\t\ts.parentNode.insertBefore(t, s);\r\n");
      out.write("\t\t\t})();\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
